### ISSUE TITLE
Extra files in hex causes weird error

### ISSUE THREAD

**Issue by Eiji7** [boydm/scenic_math#3]
Hey, I just wanted to try `scenic`, but I have a few problems with it.

## Steps to reproduce

1. `mix scenic.new app_name` command (normal output, so there is no sense to paste it her)
Of course now `deps` directory is empty which is totally normal.

2. Before I do any smallest change I simply run `mix deps.get` (as in instructions)
For now the found problem is visible. Just enter generated app directory and run command `ls deps/scenic_math/c_src/`

3. Follow tutorial by running `mix scenic.run`

## Expected behaviour

2nd point (for this version) we should see only `line.c` and `matrix.c` files

3rd point should not fail (assuming that all requirements are met)

## Current behaviour

Even in 2nd point we can see problem. Except files described in `Expected behaviour` we have 2 more i.e. `line.o` and `matrix.o`.

In 3rd point there is really weird error (for somebody who do not use `C`/`C++` language)

```bash
# skipped debug from other dependencies

==> scenic_math
mkdir -p priv
cc c_src/line.o -L/home/$USER/.asdf/installs/erlang/21.0.8/usr/lib -fPIC -shared  -dynamiclib -o priv/line.so
c_src/line.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:42: polecenia dla obiektu 'priv/line.so' nie powiodły się
make: *** [priv/line.so] Błąd 1 # here is Makefile error translated to Polish locale
could not compile dependency :scenic_math, "mix compile" failed. You can recompile this dependency with "mix deps.compile scenic_math", update it with "mix deps.update scenic_math" or clean it with "mix deps.clean scenic_math"
==> scenic_example
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. If you are using
Ubuntu or any other Debian-based system, install the packages
"build-essential". Also install "erlang-dev" package if not
included in your Erlang/OTP version. If you're on Fedora, run
"dnf group install 'Development Tools'".
```

## Found problem

I have checked twice to be sure, but from what I can see I think that you have simply forgot to clean project after publish its `hex` release. Here are files which I think should not be included:

1. `deps/scenic_math/c_src/line.o`
2. `deps/scenic_math/c_src/matrix.o`

## Current workaround

If you can confirm that in point 2 you are seeing `o` files you can simply remove them by running: `rm deps/scenic_math/c_src/*.o` (assuming that `scenic_math` is your project `hex` dependency). After it you can go to step 3.

**Comment by tcoopman** [comment]
I can confirm I had the same issue on Archlinux and I solved it by using the workaround.

**Comment by boydm** [comment]
I just pushed a fix. Can you please confirm it works for you?

**Comment by m13m** [comment]
@boydm Working fine on Fedora with this fix.

**Comment by Eiji7** [comment]
@boydm I can confirm that now after 2nd step I do not see `*.o` files and in 3rd step everything compiles well, so for me this issue is fixed.

Unfortunately after successful compile I still can't run this project properly as it's described in [forum post](https://elixirforum.com/t/problem-with-dirty-close-in-scenic/16393?u=eiji). It would be awesome if you could help me with this issue, because I really want to go deeply in your project.
